version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/my-item-stock
permissions:
  - object: /home/ec2-user/my-item-stock
    owner: ec2-user
    group: ec2-user
    mode: 755
hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 60
      runas: root